modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="dumplings_delight"
version="1.16.5-1.1"
displayName="Dumpling's Delight"
logoFile="logo.png"
logoBlur=false
authors="FoggyHillside"
description='''
'''
[[dependencies.dumplings_delight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dumplings_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dumplings_delight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.16.5-0.6.0,)"
    ordering="AFTER"
    side="BOTH"

